service: WeGit
app: wegit
org: mirrorhanyu

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: ap-southeast-1
  profile: callmehan

functions:
  trending:
    handler: trending.get_trending_repositories_and_developers
    name: trending
    environment:
      GITHUB_TRENDING_HOST: 'https://github-trending-api.now.sh'
    events:
      - http:
          path: trending
          method: get
          cors: true
          private: true

  developer:
    handler: developer.get_developer
    name: developer
    environment:
      GITHUB_API_HOST: 'https://api.github.com'
      GITHUB_ACCESS_TOKEN: ${env:GITHUB_ACCESS_TOKEN}
    events:
      - http:
          path: developer
          method: get
          cors: true
          private: true

  repository:
    handler: repository.get_repository
    name: repository
    environment:
      GITHUB_API_HOST: 'https://api.github.com'
      GITHUB_ACCESS_TOKEN: ${env:GITHUB_ACCESS_TOKEN}
    events:
      - http:
          path: repository
          method: get
          cors: true
          private: true

  search:
    handler: search.get_search
    name: search
    environment:
      GITHUB_API_HOST: 'https://api.github.com'
      GITHUB_ACCESS_TOKEN: ${env:GITHUB_ACCESS_TOKEN}
    events:
      - http:
          path: search
          method: get
          cors: true
          private: true

  event:
    handler: event.get_event
    name: event
    environment:
      GITHUB_API_HOST: 'https://api.github.com'
      GITHUB_ACCESS_TOKEN: ${env:GITHUB_ACCESS_TOKEN}
    events:
      - http:
          path: event
          method: get
          cors: true
          private: true
